language: python

python:
  - 3.6

before_install:
  - pip install -U pip setuptools wheel
  - pip install nose2 nose2-cov coverage codecov

install:
  - pip install -r requirements.txt

script:
  - nose2 -F -C --coverage-report=term-missing -v tests

after_success:
  - codecov
